In [4]:
from sklearn import datasets
import pandas as pd
import numpy as np

In [23]:
df=pd.read_csv('Iris.csv')

In [24]:
df.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [25]:
df

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [27]:
from sklearn.preprocessing import StandardScaler

In [32]:
scaler=StandardScaler

In [ ]:
df.drop(df.columns[[0,1,2,3]], axis=1, inplace=True)

In [41]:
Y=df[df.columns[5]]

In [42]:
print(Y)

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...      
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: Species, Length: 150, dtype: object


In [55]:
X=df[df.columns[[1,2,3,4]]]

In [56]:
X

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0              5.1           3.5            1.4           0.2
1              4.9           3.0            1.4           0.2
2              4.7           3.2            1.3           0.2
3              4.6           3.1            1.5           0.2
4              5.0           3.6            1.4           0.2
..             ...           ...            ...           ...
145            6.7           3.0            5.2           2.3
146            6.3           2.5            5.0           1.9
147            6.5           3.0            5.2           2.0
148            6.2           3.4            5.4           2.3
149            5.9           3.0            5.1           1.8

[150 rows x 4 columns]

In [57]:
Y

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...      
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: Species, Length: 150, dtype: object

In [15]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()

In [63]:
X_scaled=scaler.fit_transform(X)

In [64]:
Transposed=X_scaled.T

In [69]:
Covariance_matrix=np.cov(Transposed)

In [70]:
print(Covariance_matrix)

[[ 1.00671141 -0.11010327  0.87760486  0.82344326]
 [-0.11010327  1.00671141 -0.42333835 -0.358937  ]
 [ 0.87760486 -0.42333835  1.00671141  0.96921855]
 [ 0.82344326 -0.358937    0.96921855  1.00671141]]


In [71]:
value,vector=np.linalg.eig(Covariance_matrix)

In [72]:
print(value)

[2.93035378 0.92740362 0.14834223 0.02074601]


In [73]:
print(vector)

[[ 0.52237162 -0.37231836 -0.72101681  0.26199559]
 [-0.26335492 -0.92555649  0.24203288 -0.12413481]
 [ 0.58125401 -0.02109478  0.14089226 -0.80115427]
 [ 0.56561105 -0.06541577  0.6338014   0.52354627]]


In [74]:
percentage_values=[]
for i in range(len(value)):
    percentage_values.append(value[i]/np.sum(value))
print(percentage_values)

[0.7277045209380132, 0.23030523267680664, 0.03683831957627391, 0.005151926808906277]


In [75]:
projected_1=X_scaled.dot(vector.T[0])
projected_2=X_scaled.dot(vector.T[1])

In [76]:
res=pd.DataFrame(projected_1,columns=['PC1'])

In [77]:
res['PC2']=projected_2
res["Species"]=Y
print(res)

          PC1       PC2         Species
0   -2.264542 -0.505704     Iris-setosa
1   -2.086426  0.655405     Iris-setosa
2   -2.367950  0.318477     Iris-setosa
3   -2.304197  0.575368     Iris-setosa
4   -2.388777 -0.674767     Iris-setosa
..        ...       ...             ...
145  1.870522 -0.382822  Iris-virginica
146  1.558492  0.905314  Iris-virginica
147  1.520845 -0.266795  Iris-virginica
148  1.376391 -1.016362  Iris-virginica
149  0.959299  0.022284  Iris-virginica

[150 rows x 3 columns]


 # Digits Assignment 4 using PCA

In [5]:
from sklearn import datasets
digits=datasets.load_digits()

In [6]:
digitdf = pd.DataFrame(data= np.c_[digits['data'], digits['target']], #converting to dataframe
                     columns= digits['feature_names'] + ['target'])

In [7]:
digitdf

pixel_0_0  pixel_0_1  pixel_0_2  pixel_0_3  pixel_0_4  pixel_0_5  \
0           0.0        0.0        5.0       13.0        9.0        1.0   
1           0.0        0.0        0.0       12.0       13.0        5.0   
2           0.0        0.0        0.0        4.0       15.0       12.0   
3           0.0        0.0        7.0       15.0       13.0        1.0   
4           0.0        0.0        0.0        1.0       11.0        0.0   
...         ...        ...        ...        ...        ...        ...   
1792        0.0        0.0        4.0       10.0       13.0        6.0   
1793        0.0        0.0        6.0       16.0       13.0       11.0   
1794        0.0        0.0        1.0       11.0       15.0        1.0   
1795        0.0        0.0        2.0       10.0        7.0        0.0   
1796        0.0        0.0       10.0       14.0        8.0        1.0   

      pixel_0_6  pixel_0_7  pixel_1_0  pixel_1_1  ...  pixel_6_7  pixel_7_0  \
0           0.0        0.0        0.0        0.0  ...        0.0        0.0   
1           0.0        0.0        0.0        0.0  ...        0.0        0.0   
2           0.0        0.0        0.0        0.0  ...        0.0        0.0   
3           0.0        0.0        0.0        8.0  ...        0.0        0.0   
4           0.0        0.0        0.0        0.0  ...        0.0        0.0   
...         ...        ...        ...        ...  ...        ...        ...   
1792        0.0        0.0        0.0        1.0  ...        0.0        0.0   
1793        1.0        0.0        0.0        0.0  ...        0.0        0.0   
1794        0.0        0.0        0.0        0.0  ...        0.0        0.0   
1795        0.0        0.0        0.0        0.0  ...        0.0        0.0   
1796        0.0        0.0        0.0        2.0  ...        0.0        0.0   

      pixel_7_1  pixel_7_2  pixel_7_3  pixel_7_4  pixel_7_5  pixel_7_6  \
0           0.0        6.0       13.0       10.0        0.0        0.0   
1           0.0        0.0       11.0       16.0       10.0        0.0   
2           0.0        0.0        3.0       11.0       16.0        9.0   
3           0.0        7.0       13.0       13.0        9.0        0.0   
4           0.0        0.0        2.0       16.0        4.0        0.0   
...         ...        ...        ...        ...        ...        ...   
1792        0.0        2.0       14.0       15.0        9.0        0.0   
1793        0.0        6.0       16.0       14.0        6.0        0.0   
1794        0.0        2.0        9.0       13.0        6.0        0.0   
1795        0.0        5.0       12.0       16.0       12.0        0.0   
1796        1.0        8.0       12.0       14.0       12.0        1.0   

      pixel_7_7  target  
0           0.0     0.0  
1           0.0     1.0  
2           0.0     2.0  
3           0.0     3.0  
4           0.0     4.0  
...         ...     ...  
1792        0.0     9.0  
1793        0.0     0.0  
1794        0.0     8.0  
1795        0.0     9.0  
1796        0.0     8.0  

[1797 rows x 65 columns]

In [8]:
#digiY=digitdf[digitdf.columns[len(digitdf.columns)-1]]

In [9]:
digiY=digitdf.iloc[:,-1].values

In [10]:
print(digiY)

[0. 1. 2. ... 8. 9. 8.]


In [11]:
#digiX=digitdf[digitdf.columns[list(range(0,len(digitdf.columns)-1))]]

In [12]:
digiX=digitdf.iloc[:,:-1].values

In [13]:
print(digiX);

[[ 0.  0.  5. ...  0.  0.  0.]
 [ 0.  0.  0. ... 10.  0.  0.]
 [ 0.  0.  0. ... 16.  9.  0.]
 ...
 [ 0.  0.  1. ...  6.  0.  0.]
 [ 0.  0.  2. ... 12.  0.  0.]
 [ 0.  0. 10. ... 12.  1.  0.]]


In [16]:
digitsX_scaled=scaler.fit_transform(digiX)

In [17]:
digitsX_scaled

array([[ 0.        , -0.33501649, -0.04308102, ..., -1.14664746,
        -0.5056698 , -0.19600752],
       [ 0.        , -0.33501649, -1.09493684, ...,  0.54856067,
        -0.5056698 , -0.19600752],
       [ 0.        , -0.33501649, -1.09493684, ...,  1.56568555,
         1.6951369 , -0.19600752],
       ...,
       [ 0.        , -0.33501649, -0.88456568, ..., -0.12952258,
        -0.5056698 , -0.19600752],
       [ 0.        , -0.33501649, -0.67419451, ...,  0.8876023 ,
        -0.5056698 , -0.19600752],
       [ 0.        , -0.33501649,  1.00877481, ...,  0.8876023 ,
        -0.26113572, -0.19600752]])

In [18]:
TransposedDigi=digitsX_scaled.T

In [19]:
Covariance_matrix_digits=np.cov(TransposedDigi)

In [23]:
valuedigi,vectordigi=np.linalg.eig(Covariance_matrix_digits)

In [24]:
valuedigi

array([7.34477606, 5.83549054, 5.15396118, 3.96623597, 2.9663452 ,
       2.57204442, 2.40600941, 2.06867355, 1.82993314, 1.78951739,
       1.69784616, 1.57287889, 1.38870781, 1.35933609, 1.32152536,
       1.16829176, 1.08368678, 0.99977862, 0.97438293, 0.90891242,
       0.82271926, 0.77631014, 0.71155675, 0.64552365, 0.59527399,
       0.5765018 , 0.52673155, 0.5106363 , 0.48686381, 0.45560107,
       0.44285155, 0.42230086, 0.3991063 , 0.39110111, 0.36094517,
       0.34860306, 0.3195963 , 0.29406627, 0.27692285, 0.05037444,
       0.06328961, 0.258273  , 0.24783029, 0.2423566 , 0.07635394,
       0.08246812, 0.09018543, 0.09840876, 0.10250434, 0.11188655,
       0.11932898, 0.12426371, 0.13321081, 0.14311427, 0.217582  ,
       0.15818474, 0.16875236, 0.20799593, 0.17612894, 0.2000909 ,
       0.18983516, 0.        , 0.        , 0.        ])

In [25]:
vectordigi

array([[ 0.        ,  0.        ,  0.        , ...,  1.        ,
         0.        ,  0.        ],
       [ 0.18223392, -0.04702701,  0.02358821, ...,  0.        ,
         0.        ,  0.        ],
       [ 0.285868  , -0.0595648 , -0.05679875, ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [ 0.103198  ,  0.24261778, -0.02227952, ...,  0.        ,
         0.        ,  0.        ],
       [ 0.1198106 ,  0.16508926,  0.10036559, ...,  0.        ,
         0.        ,  0.        ],
       [ 0.07149362,  0.07132924,  0.09244589, ...,  0.        ,
         0.        ,  0.        ]])

In [26]:
percentage_values=[]
for i in range(len(valuedigi)):
    percentage_values.append(valuedigi[i]/np.sum(valuedigi))
print(percentage_values)

[0.12033916097734895, 0.09561054403097885, 0.08444414892624566, 0.06498407907524169, 0.04860154875966405, 0.04214119869271948, 0.0394208280356738, 0.03389380924638335, 0.029982210116252343, 0.029320025512522153, 0.027818054635503072, 0.025770550925819993, 0.022753033157642384, 0.022271797395143532, 0.021652294318492537, 0.01914166606442126, 0.017755470851681963, 0.016380692742844247, 0.015964601688623486, 0.014891911870878176, 0.013479695658179372, 0.012719313702347544, 0.011658373505919459, 0.010576465985363173, 0.0097531594719811, 0.009445589897319981, 0.008630138269707235, 0.008366428536685155, 0.00797693248411244, 0.007464713709260599, 0.007255821513702745, 0.006919112454811805, 0.006539085355726176, 0.006407925738459879, 0.0059138411172234276, 0.005711624052235246, 0.005236368034166358, 0.004818075864451442, 0.004537192598584503, 0.0008253509448180257, 0.0010369573015571818, 0.004231627532327803, 0.004060530699790387, 0.003970848082758281, 0.001251007424973024, 0.00135118411337086

In [27]:
count=0  #getting required components for accuracy of 95% and above 
sum=0 
for i in percentage_values:
    sum=sum+i
    count=count+1
    if(sum>0.95):
        break

In [28]:
count

42

In [33]:
res=pd.DataFrame(digitsX_scaled.dot(vectordigi.T[0]),columns=['PC1']) #making dataframe
sname='PC'
for i in range(42):
    res[sname+str(i+2)]=digitsX_scaled.dot(vectordigi.T[i+1])

In [37]:
res['Target']=digiY

In [38]:
res

PC1       PC2       PC3       PC4       PC5       PC6       PC7  \
0    -1.914214  0.954502 -3.946035 -2.028723 -0.267173  0.530327  1.415321   
1    -0.588980 -0.924636  3.924755  1.779850 -0.993430 -0.675652 -1.878565   
2    -1.302039  0.317189  3.023333  2.043376 -2.081155  0.935121  1.296200   
3     3.020770  0.868772 -0.801744  2.187039 -0.556813  0.727124 -0.959766   
4    -4.528949  1.093480  0.973121  1.419510 -1.715106  1.431592 -1.073649   
...        ...       ...       ...       ...       ...       ...       ...   
1792 -0.104331 -0.255024 -3.765861  1.947006 -0.190094 -0.555760 -0.531222   
1793 -2.423234  1.429611 -3.045245 -2.632089 -0.822902  0.004061  1.106872   
1794 -1.022596  0.147911  2.469974  0.620307 -0.972043 -0.007377 -0.381115   
1795 -1.076055  0.380906 -2.455487  1.312013  0.253533 -0.638322 -1.034470   
1796  1.257702  2.227591  0.283628  0.127073 -1.570173  2.342953  0.383075   

           PC8       PC9      PC10  ...      PC35      PC36      PC37  \
0    -1.496062 -0.124914 -0.822246  ...  0.117190  0.709049  0.082410   
1    -0.556336 -1.079877  0.087451  ... -0.671299 -0.004144 -0.246765   
2    -1.156160 -0.785606 -1.099206  ...  0.149503 -0.089290  0.408216   
3     1.382638 -0.259075  0.744555  ... -0.148854  0.234044  0.396726   
4     0.968240  1.660216  1.174593  ... -0.263106 -0.583008 -0.174328   
...        ...       ...       ...  ...       ...       ...       ...   
1792 -0.476475 -1.152430 -0.473054  ...  0.392554  0.420797  0.541567   
1793 -2.330903 -0.569455 -1.654173  ... -0.169494 -0.023170 -0.162096   
1794 -0.529064 -2.054709 -2.036838  ...  1.019822  0.134728 -0.543296   
1795 -0.763325 -1.077474 -0.334527  ... -0.771848  0.576100  0.429805   
1796  1.200566 -0.816831 -1.825428  ... -0.548583 -0.763627 -0.266967   

          PC38      PC39      PC40      PC41      PC42      PC43  Target  
0     0.814059  0.024931 -0.027512  0.009188  0.321931 -0.013868     0.0  
1     0.200261  0.087108 -0.103101 -0.127878 -0.489143  0.001026     1.0  
2    -0.214596 -1.278875  0.179429  0.518823  0.545834  0.344005     2.0  
3     0.197436  0.772751  0.101748  0.115922 -0.050325 -0.500999     3.0  
4    -0.215579 -0.133426 -0.072045  0.084901  0.184994  0.184324     4.0  
...        ...       ...       ...       ...       ...       ...     ...  
1792 -0.024422 -0.756333  0.111765 -0.009942 -0.285562  0.152253     9.0  
1793 -0.506573 -0.061084 -0.138655 -0.374617 -0.404112 -0.502122     0.0  
1794  0.601365  0.412388 -0.102153 -0.061053  1.208864  0.530791     8.0  
1795  0.437566 -0.698635 -0.594146  0.306155 -0.443400 -0.173600     9.0  
1796 -0.381086  0.128551  0.226830  0.114960  1.321372 -0.160506     8.0  

[1797 rows x 44 columns]