In [1]:
import numpy as np

In [2]:
x=np.array([1,2,3,4,5,6])

In [3]:
print(x)

[1 2 3 4 5 6]


In [4]:
x[0]

1

In [5]:
x[1]

2

In [6]:
x[-1]

6

In [7]:
l1=[2,4,5,6]

In [8]:
l1.append(8)

In [9]:
l1

[2, 4, 5, 6, 8]

In [10]:
x.append(70)

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [11]:
print(x+1)

[2 3 4 5 6 7]


In [12]:
print(l1+1)

TypeError: can only concatenate list (not "int") to list

In [13]:
x=np.array([1,2,3,4,5,6])

In [15]:
print(x[2:5])

[3 4 5]


In [16]:
x

array([1, 2, 3, 4, 5, 6])

In [17]:
print(x)

[1 2 3 4 5 6]


In [18]:
print(type(x))

<class 'numpy.ndarray'>


In [19]:
y=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [20]:
print(y)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [21]:
print(y.shape)

(4, 3)


In [22]:
print(x.shape)

(6,)


In [23]:
print(1:4,1:3)

SyntaxError: invalid syntax (<ipython-input-23-d250b7739290>, line 1)

In [24]:
y[1:4,1:3]

array([[ 5,  6],
       [ 8,  9],
       [11, 12]])

In [25]:
y[1:,1:]

array([[ 5,  6],
       [ 8,  9],
       [11, 12]])

In [26]:
x=np.array([1,12,3,4,6,7])

In [27]:
x[:3]

array([ 1, 12,  3])

In [28]:
x=np.arange(10,30,2)

In [29]:
print(x)

[10 12 14 16 18 20 22 24 26 28]


In [30]:
x=np.arange(10,30)

In [31]:
print(x)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]


In [32]:
x=np.linspace(3,10,3)

In [33]:
print(x)

[ 3.   6.5 10. ]


In [34]:
x=np.zeros(10)

In [35]:
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [38]:
x=np.zeros((10),dtype=np.int32)

In [39]:
print(x)

[0 0 0 0 0 0 0 0 0 0]


In [40]:
y=np.ones(10)

In [41]:
print(y)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [43]:
y=np.ones((10),dtype=np.int32)*5
print(y)

[5 5 5 5 5 5 5 5 5 5]


In [47]:
x=np.full([3,4],"hello")

In [48]:
print(x)

[['hello' 'hello' 'hello' 'hello']
 ['hello' 'hello' 'hello' 'hello']
 ['hello' 'hello' 'hello' 'hello']]


In [49]:
x=np.ones((10),dtype=np.int32)*5
print(x)

[5 5 5 5 5 5 5 5 5 5]


In [50]:
x=np.arange(10,51)

In [51]:
print(x)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [52]:
x=np.arange(10,51,2)
print(x)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [54]:
y=np.arange(0,9).reshape(3,3)
print(y)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [55]:
y=np.arange(0,9)
print(y.reshape(3,3))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [56]:
np.arange(0,1.01,0.01)

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ,
       0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21,
       0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32,
       0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43,
       0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54,
       0.55, 0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65,
       0.66, 0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76,
       0.77, 0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87,
       0.88, 0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98,
       0.99, 1.  ])

In [58]:
y=np.random.normal(size=25)
print(y)

[-0.06373504 -1.57477896 -2.92489996  0.23465043 -0.67381489  0.51232659
 -1.88340548 -0.25018204  0.68209888  2.30911239  0.64028586 -0.84485583
  1.47534124  1.45396614 -0.77969441 -0.0382359   0.38595578  1.46887085
 -0.4241606  -2.32969276 -0.75432051 -0.38856678 -0.73349133  0.97288295
  0.58175556]


In [59]:
z=np.linspace(0,1,20)
print(z)

[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


In [64]:
mat=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])

In [65]:
print(mat)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [66]:
print(mat.shape)

(5, 5)


In [68]:
print(mat[2:5,1:5])

[[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]


In [69]:
print(0:3,1)

SyntaxError: invalid syntax (<ipython-input-69-5dd39f65103f>, line 1)

In [70]:
print(mat[0:3,1])

[ 2  7 12]


In [78]:
def ssum(arr):
        sum=0
for i in range(0,5):
    for j in range(0,5):
        sum=sum+mat[i][j]
print("sum is" , sum)

sum=0

row sum is 975


In [79]:
def column_sum(arr) :
 
    sum = 0
 
    # finding the row sum
    for i in range(0,5) :
        for j in range(0,5) :
 
            # Add the element
            sum += mat[j][i]
 
        # Print the row sum
        print("Sum of the column",i,"=",sum)
 
        # Reset the sum
        sum = 0

In [80]:
row_sum(mat)


Finding Sum of each row:

Sum of the column 0 = 55
Sum of the column 1 = 60
Sum of the column 2 = 65
Sum of the column 3 = 70
Sum of the column 4 = 75


In [ ]:
def row_sum(arr) :
 
    sum = 0
 
    # finding the row sum
    for i in range(0,5) :
        for j in range(0,5) :
 
            # Add the element
            sum += mat[i][j]
 
        # Print the row sum
        print("Sum of the row",i,"=",sum)
 
        # Reset the sum
        sum = 0